spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
            exposed-headers: "*"
      routes:
        - id: r0
          uri: http://localhost:8095
          predicates:
            - Path= /auths/api/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: r2
          uri: http://localhost:9528
          predicates:
            - Path= /messages/api/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: r3
          uri: http://localhost:9510
          predicates:
            - Path= /payments/api/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: r4
          uri: http://192.168.194.129:6500/
          predicates:
            - Path= /models/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: true
  application:
    name: gateway-service
server:
  port: 8888
