################################# STOMP #############################################################
stomp:
  websocket:
    server:
      address:ws://localhost:9528/private-channel
    destination:
      private:/queue/private-channel
      public:/topic/public-channel
################################# MONGODB #############################################################
spring:
  data:
    mongodb:
      username:sigma
      password:Sigma-Labs-12345
      authentication-database:admin
      host=localhost
      port:27017
      database:stomp-websocket-data
  ################################# DISCOVERY #############################################################
  cloud:
    discovery:
      enabled:true
eureka:
  client:
    service-url:
      defaultZone:http://localhost:8761/eureka
  instance:
    prefer-ip-address:true